name: Ghpages

on:
  pull_request:
    types: [ labeled ]

jobs:
  release:
    name: Ghpages

    if: ${{ github.event.label.name == 'ghpages' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install NPM
        run: npm i -g npm@^6

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Publish doc-site for the latest (published) semver release
      - name: Build doc-site
        run: npm run install:docs && npm run build:docs:prod && npm run playroom:build

      - name: Publish doc-site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc-site/public
