name: Test

on: pull_request

jobs:

  validate:
    name: Code quality validations
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup Eslint Checks
      uses: mrdivyansh/eslint-action@v1.0.7
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        eslint-rc: .eslintrc.js